name: My Workflow Linter

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: devops-actions/actionlint@v0.1.2
